name: LSL Syntax Check

on:
  push:
    paths:
      - '**/*.lsl'
      - '.github/workflows/lsl-check.yml'
  pull_request:
    paths:
      - '**/*.lsl'
      - '.github/workflows/lsl-check.yml'

permissions: read-all

jobs:
  lsl-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential cmake flex bison

      - name: Build and install lslint
        run: |
          git clone --depth=1 https://github.com/Makopo/lslint.git
          cd lslint
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
          sudo make install
          lslint --version || true

      - name: Run lslint on all .lsl files
        run: |
          set -e
          mapfile -t files < <(git ls-files '*.lsl')
          if [ ${#files[@]} -eq 0 ]; then
            echo "No .lsl files to check."
            exit 0
          fi
          echo "Checking ${#files[@]} LSL files..."
          # Run lslint; fail if any file has a syntax error
          lslint "${files[@]}" | tee lslint-output.txt
          # Write summary
          {
            echo "## lslint results"
            echo
            if [ -s lslint-output.txt ]; then
              echo '```'
              cat lslint-output.txt
              echo '```'
            else
              echo "No output from lslint."
            fi
          } >> "$GITHUB_STEP_SUMMARY"
